import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#7c5cfc",
        "primary-deep": "#5c3dd9",
        "on-primary": "#ffffff",
        twilight: {
          300: "#c4b5fd",
          500: "#a78bfa",
          700: "#7c5cfc",
          800: "#6366f1",
          900: "#4f46e5",
        },
        "blue-saturated": "#4f8cf7",
        cream: "#fff8e0",
        "cream-light": "#fffaeb",
        "cream-deeper": "#fff0c2",
        "beige-deep": "#e6d5a8",
        ink: "#1f1f1f",
        "ink-tint": "#3d3d3d",
        charcoal: "#2c2c2c",
        slate: "#4a4a4a",
        steel: "#6a6a6a",
        stone: "#8a8a8a",
        muted: "#a8a8a8",
        hairline: "#e5e5e5",
        "hairline-soft": "#ededed",
        "hairline-strong": "#c7c7c7",
        canvas: "#ffffff",
        surface: "#fafafa",
        "surface-cream": "#fff8e0",
        "surface-cream-soft": "#fffaeb",
        "surface-code": "#1c1c1e",
        "on-dark": "#ffffff",
        "on-dark-muted": "#a8a8a8",
        "on-cream": "#1f1f1f",
        "footer-cream": "#fff8e0",
        link: "#7c5cfc",
        success: "#22C55E",
        warning: "#F59E0B",
        error: "#EF4444",
      },
      fontFamily: {
        display: ["var(--font-display)", "serif"],
        body: ["var(--font-body)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        "hero-display": ["84px", { lineHeight: "1.05", letterSpacing: "-1.5px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.10", letterSpacing: "-1px", fontWeight: "400" }],
        "h1-display": ["52px", { lineHeight: "1.15", letterSpacing: "-0.5px", fontWeight: "400" }],
        h2: ["36px", { lineHeight: "1.20", letterSpacing: "-0.5px", fontWeight: "500" }],
        h3: ["28px", { lineHeight: "1.25", fontWeight: "500" }],
        h4: ["22px", { lineHeight: "1.30", fontWeight: "500" }],
        h5: ["18px", { lineHeight: "1.40", fontWeight: "500" }],
        subtitle: ["18px", { lineHeight: "1.50", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.55", fontWeight: "400" }],
        "body-md-medium": ["16px", { lineHeight: "1.55", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.50", fontWeight: "400" }],
        "body-sm-medium": ["14px", { lineHeight: "1.50", fontWeight: "500" }],
        caption: ["13px", { lineHeight: "1.40", fontWeight: "400" }],
        "caption-bold": ["13px", { lineHeight: "1.40", fontWeight: "600" }],
        micro: ["12px", { lineHeight: "1.40", fontWeight: "500" }],
        "micro-uppercase": ["11px", { lineHeight: "1.40", fontWeight: "600", letterSpacing: "1px" }],
        "button-md": ["14px", { lineHeight: "1.30", fontWeight: "500" }],
        "stat-display": ["56px", { lineHeight: "1.10", letterSpacing: "-1px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "1.50", fontWeight: "400" }],
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "20px",
        xl: "24px",
        xxl: "32px",
        xxxl: "40px",
        "section-sm": "48px",
        section: "64px",
        "section-lg": "96px",
        hero: "120px",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        xxl: "20px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(26, 21, 37, 0.06)",
        md: "0 4px 12px rgba(26, 21, 37, 0.08)",
        lg: "0 8px 24px rgba(26, 21, 37, 0.12)",
        "focus-ring": "0 0 0 2px #7c5cfc",
      },
    },
  },
  plugins: [],
};

export default config;
